import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import { ClerkProvider } from '@clerk/nextjs'
import { CartProvider } from "./_context/CartContext";


const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <CartProvider>
      <html lang="en">
      <body className={inter.className}>
        <main className="pt-8 bg-gray">
          <Navbar/>
             {children}
          <Footer/>
        </main>
      </body>
    </html>
    </CartProvider>
    </ClerkProvider>
  );
}
